<?php

namespace Restaurants;

use FoodItems\FoodItem;
use Invoices\Invoice;
use Persons\Employees\Cashier;

class Restaurant {
    private array $menu;
    private array $employees; 

    public function __construct(array $menu, array $employees) {
        $this->menu = $menu;
        $this->employees = $employees;
    }

    public function order(array $order): Invoice {
        $cashier = $this->getCashier();
        if (!$cashier) {
            throw new \Exception('No cashier available');
        }

        $foodOrder = $cashier->generateOrder($order, $this);

        echo "Order generated by cashier\n";
        $invoice = new Invoice();
        return $invoice;
    }

    public function getMenuCategories(): array {
        return array_map(function(FoodItem $item) {
            return $item->getCategory();
        }, $this->menu);
    }

    private function getCashier(): ?Cashier {
        foreach ($this->employees as $employee) {
            if ($employee instanceof Cashier) {
                return $employee;
            }
        }
        return null;
    }
}
